name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy when pushing to main
  pull_request:
    branches:
      - main  # Deploy when creating a pull request to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0  # Adjust based on your project

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install Playwright
      - name: Install Playwright
        run: sudo npx playwright install-deps

      # Step 5: Build the Project
      - name: Build Application
        run: npm run build

      # Step 6: Start the Server
      - name: Start Server
        run: npm run start &

      # Step 7: Wait for App to be Ready
      - name: Wait for App to be Ready
        run: npx wait-on http://localhost:3000

      # Step 8: Run Playwright Tests
      - name: Run Playwright Tests
        run: npm run test

      # Step 9: Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
