name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Deploy when pushing to main
  pull_request:
    branches:
      - main  # Deploy when creating a pull request to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0  # Adjust based on your project

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build the Project (Optional for Next.js)
      - name: Build Project
        run: npm run build

      # Step 5: Deploy to Vercel
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
